name: Test setup-dune Action

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            version: nightly
            steps: all
            ocaml-version: '5.3.0'
            display: short
            extraname: ' with OCaml version'
            fault: false
    name: ${{ matrix.version }} on ${{ matrix.runs-on }}${{ matrix.extraname }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout `graphics`
        uses: actions/checkout@v4
        with:
          repository: ocaml/graphics
          ref: refs/tags/5.2.0
          path: graphics
      - name: Ensure compatibility with Duneâ€™s version
        run: |
          printf '(lang dune 3.18)\n(lock_dir (constraints (dune (= %s))))\n' \
            ${{ matrix.version }} > graphics/dune-workspace
        if: ${{ startsWith(matrix.version, '3') }}
      - name: Create `dune-workspace`
        run: |
          printf '(lang dune 3.18)\n(lock_dir (constraints (ocaml (= 5.2.0))))\n' \
            > graphics/dune-workspace
      - name: Use local setup-dune action
        uses: ./
        with:
          version: ${{ matrix.version }}
          steps: ${{ matrix.steps }}
          directory: graphics
          workspace: ${{ matrix.workspace }}
          ocaml-version: ${{ matrix.ocaml-version }}
          display: ${{ matrix.display }}
        continue-on-error: ${{ matrix.fault }}
      - name: Show dune version
        run: dune --version
