name: Test setup-dune Action

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            version: nightly
            steps: all
            workspace: dune-workspace.ci
            display: short
            extraname: ' with workspace'
            cache-prefix: 'ws'
            fault: false
          - runs-on: ubuntu-latest
            version: latest
            steps: all
            workspace: dune-workspace.ci
            context: ocaml-5.3.0
            display: verbose
            extraname: ' with context'
            cache-prefix: 'ws'
            fault: false
    name: ${{ matrix.version }} on ${{ matrix.runs-on }}${{ matrix.extraname }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout `graphics`
        uses: actions/checkout@v4
        with:
          repository: ocaml/graphics
          ref: refs/tags/5.2.0
          path: graphics
      - name: Ensure compatibility with Duneâ€™s version
        run: |
          printf '(lang dune 3.18)\n(lock_dir (constraints (dune (= %s))))\n' \
            ${{ matrix.version }} > graphics/dune-workspace
        if: ${{ startsWith(matrix.version, '3') }}
      - name: Create `dune-workspace.ci`
        env:
          WS: |
            (lang dune 3.18)

            (context default)

            (context
             (default
              (name ocaml-%s)
              (lock_dir ocaml-%s.lock)))

            (lock_dir
             (path ocaml-%s.lock)
             (constraints
              (ocaml
               (= %s))))
          VERSION: "5.3.0"
        run: |
          printf "$WS" "$VERSION" "$VERSION" "$VERSION" "$VERSION" \
            > graphics/dune-workspace.ci
          (set -x; cat graphics/dune-workspace.ci)
        if: ${{ matrix.workspace == 'dune-workspace.ci' }}
      - name: Use local setup-dune action
        uses: ./
        with:
          version: ${{ matrix.version }}
          steps: ${{ matrix.steps }}
          directory: graphics
          workspace: ${{ matrix.workspace }}
          display: ${{ matrix.display }}
          cache-prefix: ${{ matrix.cache-prefix }}
        continue-on-error: ${{ matrix.fault }}
      - name: Show dune version
        run: dune --version
