name: Test setup-dune Action

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
        version: [nightly, latest, 3.19.1]
        steps: ['install-dune enable-pkg lazy-update-depexts install-depexts build runtest']
        workspace: ['']
        display: ['short']
        fault: [false]
        include:
          - # A strange case: faulty because it doesn’t install the depexts,
            # using a specific dune-workspace and with verbose log
            runs-on: ubuntu-latest
            version: nightly
            steps: 'install-dune enable-pkg build runtest'
            workspace: dune-workspace.ci
            display: verbose
            extraname: ' with workspace'
            fault: true
          - runs-on: macos-15-intel
            version: nightly
            steps: all
            display: short
            fault: false
    name: ${{ matrix.version }} on ${{ matrix.runs-on }}${{ matrix.extraname }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout `graphics`
        uses: actions/checkout@v4
        with:
          repository: ocaml/graphics
          ref: refs/tags/5.2.0
          path: graphics
      - name: Ensure compatibility with Dune’s version
        run: |
          printf '(lang dune 3.18)\n(lock_dir (constraints (dune (= %s))))\n' \
            ${{ matrix.version }} > graphics/dune-workspace
        if: ${{ startsWith(matrix.version, '3') }}
      - name: Create `dune-workspace.ci`
        run: |
          printf '(lang dune 3.18)\n(lock_dir (constraints (ocaml (= 5.3.0))))\n' \
            > graphics/dune-workspace.ci
        if: ${{ matrix.workspace == 'dune-workspace.ci' }}
      - name: Use local setup-dune action
        uses: ./
        with:
          version: ${{ matrix.version }}
          steps: ${{ matrix.steps }}
          directory: graphics
          workspace: ${{ matrix.workspace }}
          display: ${{ matrix.display }}
        continue-on-error: ${{ matrix.fault }}
      - name: Show dune version
        run: dune --version
